/*
 * WeeklyPrep — Auto-generated XFN Leadership Weekly
 * Pulls from all 4 modules to generate a pre-read for the weekly standup.
 * Beth reviews and edits before the meeting. This is the "second brain" in action.
 */
import Layout from "@/components/Layout";
import { motion } from "framer-motion";
import { useAgent } from "@/contexts/AgentContext";
import { modules, getTotalStats } from "@/lib/data";
import {
  Calendar,
  Clock,
  AlertTriangle,
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  RefreshCw,
  FileText,
  Users,
  Target,
  Zap,
  ChevronDown,
  MessageSquare,
} from "lucide-react";
import { useState } from "react";

const fade = { initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 } };

// Simulated weekly prep data — in production, this would be generated by agents
const weeklyPrepData = {
  generatedAt: new Date().toISOString(),
  weekOf: new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }),
  executiveSummary:
    "CTV pipeline continues to build with 12 active opportunities ($4.2M weighted). Three deals advancing to negotiation stage. Key risk: brand safety certification delay may impact Q2 close targets. ML performance data from latest tests supports conviction on Learning Goal #1. Web product beta timeline slipping — needs XFN escalation.",
  moduleHighlights: [
    {
      moduleId: 1,
      title: "Market Intelligence",
      status: "green" as const,
      keyInsight:
        "Competitor tvScientific launched incrementality measurement. Three analyst reports this week emphasize this capability. Our positioning needs to address this gap.",
      actionItems: [
        "Update battlecards with tvScientific incrementality feature",
        "Draft counter-positioning messaging emphasizing ML optimization advantage",
        "Schedule product discussion on incrementality roadmap",
      ],
      metrics: { signalsDetected: 47, battlecardsUpdated: 3, positioningGaps: 1 },
    },
    {
      moduleId: 2,
      title: "Distribution & Pipeline",
      status: "yellow" as const,
      keyInsight:
        "Outbound cycle #7 showed 4.2% email response rate (up from 3.1%). Gaming vertical continues to convert best. Digital awareness campaigns generating qualified traffic but nurture-to-SQL conversion needs work.",
      actionItems: [
        "Double down on gaming vertical outbound",
        "Review nurture sequence for consideration stage drop-off",
        "Approve next round of A/B test variants for outbound messaging",
      ],
      metrics: { activeOpportunities: 12, pipelineValue: "$4.2M", responseRate: "4.2%" },
    },
    {
      moduleId: 3,
      title: "Customer Success",
      status: "green" as const,
      keyInsight:
        "Two active tests showing strong performance. Account ABC exceeding ROAS targets by 25%. Account DEF showing early positive signals but needs creative refresh. One case study candidate identified.",
      actionItems: [
        "Prepare 4-week readout for Account ABC",
        "Coordinate creative refresh for Account DEF with GDS",
        "Begin case study interview process for Account ABC",
      ],
      metrics: { activeTests: 5, avgROAS: "+18%", healthScore: "7.2/10" },
    },
    {
      moduleId: 4,
      title: "Governance & BI",
      status: "red" as const,
      keyInsight:
        "Test fund utilization at 67% committed, 42% deployed. $180K remaining. ARR pacing below target — need to accelerate pipeline conversion. Brand safety certification is the critical blocker for 2 deals in negotiation.",
      actionItems: [
        "Escalate brand safety certification timeline to Product",
        "Review test fund allocation — consider rebalancing from underperforming tests",
        "Prepare EOQ2 conviction update for leadership",
      ],
      metrics: { testFundRemaining: "$180K", arrPacing: "Below target", blockers: 2 },
    },
  ],
  xfnDiscussionItems: [
    {
      topic: "Brand Safety Certification Timeline",
      owner: "Product / Engineering",
      urgency: "high" as const,
      context: "Two deals in negotiation stage require brand safety certification. Current timeline is 6 weeks — need to explore acceleration options.",
    },
    {
      topic: "Web Product Beta Readiness",
      owner: "Product / Engineering",
      urgency: "high" as const,
      context: "Beta timeline slipping by 2 weeks. Impact on CTV-to-Web pipeline development and Learning Goal #4 conviction.",
    },
    {
      topic: "GDS Support for Campaign Optimization",
      owner: "GDS / Data Science",
      urgency: "medium" as const,
      context: "Request for dedicated DS support for CTV test optimization. Currently relying on Asia-based team with timezone challenges.",
    },
    {
      topic: "Creative Studio Capacity for CTV",
      owner: "Creative Studio",
      urgency: "medium" as const,
      context: "Need creative refresh for 2 accounts and new creative sets for 3 upcoming tests. Current queue is 3 weeks.",
    },
    {
      topic: "Legal Review for Test Fund Contracts",
      owner: "Legal / Finance",
      urgency: "low" as const,
      context: "Standardized test fund contract template needed to accelerate deal closing. Currently each contract requires individual legal review.",
    },
  ],
  keyDecisionsNeeded: [
    "Approve reallocation of $50K test fund from underperforming Account GHI to new gaming vertical prospect",
    "Decide whether to accelerate brand safety certification (requires engineering resource trade-off)",
    "Approve next round of outbound messaging variants (3 new angles based on cycle #7 learnings)",
    "Confirm CTV presence at upcoming AdExchanger conference (budget: $15K, 2 speaking slots available)",
  ],
  learningGoalUpdates: [
    { goal: "ML Performance", direction: "up" as const, note: "Latest tests support conviction. Moving from moderate to strong." },
    { goal: "Repeatable ICP", direction: "up" as const, note: "Gaming vertical signal strengthening. Need 2 more data points." },
    { goal: "2-FTE Model", direction: "flat" as const, note: "Content approval bottleneck identified. Exploring async approval workflow." },
    { goal: "CTV-to-Web Viability", direction: "down" as const, note: "Beta delay impacts timeline. Insufficient data for conviction." },
  ],
};

function StatusBadge({ status }: { status: "green" | "yellow" | "red" }) {
  const colors = {
    green: "bg-emerald-100 text-emerald-700 border-emerald-200",
    yellow: "bg-amber-100 text-amber-700 border-amber-200",
    red: "bg-red-100 text-red-700 border-red-200",
  };
  const labels = { green: "On Track", yellow: "Needs Attention", red: "At Risk" };
  return (
    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${colors[status]}`}>
      {labels[status]}
    </span>
  );
}

function UrgencyBadge({ urgency }: { urgency: "high" | "medium" | "low" }) {
  const colors = {
    high: "bg-red-500 text-white",
    medium: "bg-amber-500 text-white",
    low: "bg-gray-400 text-white",
  };
  return (
    <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${colors[urgency]} uppercase`}>
      {urgency}
    </span>
  );
}

export default function WeeklyPrep() {
  const { recentRuns, runAgent } = useAgent();
  const [expandedModules, setExpandedModules] = useState<Set<number>>(new Set([1, 2, 3, 4]));
  const [isRegenerating, setIsRegenerating] = useState(false);
  const stats = getTotalStats();

  const toggleModule = (id: number) => {
    setExpandedModules((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const handleRegenerate = () => {
    setIsRegenerating(true);
    // Simulate regeneration
    runAgent(168, "Generate weekly executive reports", 4, "XFN Leadership Weekly Preparation");
    setTimeout(() => setIsRegenerating(false), 3000);
  };

  return (
    <Layout>
      <div className="p-4 sm:p-6 lg:p-8 max-w-[1000px]">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-6">
          <div>
            <div className="flex items-center gap-2 text-xs text-muted-foreground mb-2">
              <Calendar className="w-3.5 h-3.5" />
              <span>Week of {weeklyPrepData.weekOf}</span>
            </div>
            <h1 className="text-xl sm:text-2xl font-semibold tracking-tight">
              XFN Leadership Weekly
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              Auto-generated pre-read from all {stats.modules} modules · {stats.totalPrompts} agents
            </p>
          </div>
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating}
            className="flex items-center gap-2 px-4 py-2 bg-[#0091FF] text-white text-sm font-medium rounded-lg hover:bg-[#0080E0] transition-colors disabled:opacity-60 shrink-0"
          >
            <RefreshCw className={`w-4 h-4 ${isRegenerating ? "animate-spin" : ""}`} />
            {isRegenerating ? "Regenerating..." : "Regenerate"}
          </button>
        </div>

        {/* Auto-generated badge */}
        <motion.div {...fade} className="flex items-center gap-2 px-3 py-2 bg-[#0091FF]/5 border border-[#0091FF]/20 rounded-lg mb-6 text-xs">
          <Zap className="w-3.5 h-3.5 text-[#0091FF]" />
          <span className="text-[#0091FF] font-medium">Agent-generated</span>
          <span className="text-muted-foreground">
            · Last generated {new Date(weeklyPrepData.generatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
            · Pulls from Modules 1-4, Gong, SFDC, Sensor Tower
          </span>
        </motion.div>

        {/* Executive Summary */}
        <motion.div {...fade} transition={{ delay: 0.05 }} className="bg-white border border-border rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-4 h-4 text-[#0091FF]" />
            <h2 className="text-sm font-semibold uppercase tracking-wider">Executive Summary</h2>
          </div>
          <p className="text-sm leading-relaxed text-foreground/90">{weeklyPrepData.executiveSummary}</p>
        </motion.div>

        {/* Module Highlights */}
        <motion.div {...fade} transition={{ delay: 0.1 }} className="mb-6">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-3 px-1">
            Module Highlights
          </h2>
          <div className="space-y-3">
            {weeklyPrepData.moduleHighlights.map((mh) => (
              <div key={mh.moduleId} className="bg-white border border-border rounded-xl overflow-hidden">
                <button
                  onClick={() => toggleModule(mh.moduleId)}
                  className="w-full flex items-center justify-between p-4 hover:bg-muted/30 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-[#0091FF]/10 flex items-center justify-center text-[#0091FF] font-bold text-sm">
                      M{mh.moduleId}
                    </div>
                    <div className="text-left">
                      <div className="text-sm font-medium">{mh.title}</div>
                    </div>
                    <StatusBadge status={mh.status} />
                  </div>
                  <ChevronDown
                    className={`w-4 h-4 text-muted-foreground transition-transform ${
                      expandedModules.has(mh.moduleId) ? "rotate-180" : ""
                    }`}
                  />
                </button>
                {expandedModules.has(mh.moduleId) && (
                  <div className="px-4 pb-4 border-t border-border/50">
                    {/* Key Insight */}
                    <div className="mt-3 mb-3">
                      <div className="text-[11px] font-semibold text-muted-foreground uppercase mb-1">Key Insight</div>
                      <p className="text-sm text-foreground/80">{mh.keyInsight}</p>
                    </div>

                    {/* Metrics */}
                    <div className="grid grid-cols-3 gap-2 mb-3">
                      {Object.entries(mh.metrics).map(([key, val]) => (
                        <div key={key} className="bg-muted/50 rounded-lg px-3 py-2">
                          <div className="text-[10px] text-muted-foreground capitalize">
                            {key.replace(/([A-Z])/g, " $1").trim()}
                          </div>
                          <div className="text-sm font-semibold mt-0.5">{val}</div>
                        </div>
                      ))}
                    </div>

                    {/* Action Items */}
                    <div>
                      <div className="text-[11px] font-semibold text-muted-foreground uppercase mb-1.5">Action Items</div>
                      <div className="space-y-1.5">
                        {mh.actionItems.map((item, i) => (
                          <div key={i} className="flex items-start gap-2 text-sm">
                            <ArrowRight className="w-3.5 h-3.5 text-[#0091FF] mt-0.5 shrink-0" />
                            <span className="text-foreground/80">{item}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </motion.div>

        {/* XFN Discussion Items */}
        <motion.div {...fade} transition={{ delay: 0.15 }} className="bg-white border border-border rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <Users className="w-4 h-4 text-[#0091FF]" />
            <h2 className="text-sm font-semibold uppercase tracking-wider">XFN Discussion Items</h2>
          </div>
          <div className="space-y-3">
            {weeklyPrepData.xfnDiscussionItems.map((item, i) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                <div className="mt-0.5">
                  <UrgencyBadge urgency={item.urgency} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium">{item.topic}</div>
                  <div className="text-[11px] text-[#0091FF] font-medium mt-0.5">{item.owner}</div>
                  <div className="text-xs text-muted-foreground mt-1">{item.context}</div>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Key Decisions Needed */}
        <motion.div {...fade} transition={{ delay: 0.2 }} className="bg-white border border-border rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <AlertTriangle className="w-4 h-4 text-amber-500" />
            <h2 className="text-sm font-semibold uppercase tracking-wider">Key Decisions Needed</h2>
          </div>
          <div className="space-y-2">
            {weeklyPrepData.keyDecisionsNeeded.map((decision, i) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-amber-50 border border-amber-100 rounded-lg">
                <span className="w-5 h-5 rounded-full bg-amber-200 text-amber-800 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <span className="text-sm text-foreground/80">{decision}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Learning Goal Updates */}
        <motion.div {...fade} transition={{ delay: 0.25 }} className="bg-white border border-border rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <Target className="w-4 h-4 text-[#0091FF]" />
            <h2 className="text-sm font-semibold uppercase tracking-wider">Learning Goal Updates</h2>
          </div>
          <div className="space-y-2">
            {weeklyPrepData.learningGoalUpdates.map((lg, i) => (
              <div key={i} className="flex items-center gap-3 p-3 bg-muted/30 rounded-lg">
                <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 ${
                  lg.direction === "up" ? "bg-emerald-100 text-emerald-600" :
                  lg.direction === "down" ? "bg-red-100 text-red-600" :
                  "bg-gray-100 text-gray-500"
                }`}>
                  <TrendingUp className={`w-3.5 h-3.5 ${
                    lg.direction === "down" ? "rotate-180" : lg.direction === "flat" ? "rotate-0" : ""
                  }`} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium">{lg.goal}</div>
                  <div className="text-xs text-muted-foreground mt-0.5">{lg.note}</div>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Recent Agent Activity */}
        {recentRuns.length > 0 && (
          <motion.div {...fade} transition={{ delay: 0.3 }} className="bg-white border border-border rounded-xl p-5">
            <div className="flex items-center gap-2 mb-4">
              <MessageSquare className="w-4 h-4 text-[#0091FF]" />
              <h2 className="text-sm font-semibold uppercase tracking-wider">Recent Agent Activity</h2>
            </div>
            <div className="space-y-2">
              {recentRuns.slice(0, 5).map((run) => (
                <div key={run.id} className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/30">
                  <div className={`w-2 h-2 rounded-full shrink-0 ${
                    run.status === "running" ? "bg-amber-400 animate-pulse" :
                    run.status === "completed" ? "bg-emerald-400" : "bg-red-400"
                  }`} />
                  <div className="flex-1 min-w-0">
                    <div className="text-xs truncate">Prompt #{run.promptId}: {run.promptText.slice(0, 60)}...</div>
                    <div className="text-[10px] text-muted-foreground font-mono">
                      {new Date(run.startedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                      {run.status === "completed" && " · completed"}
                      {run.status === "running" && " · running..."}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>
        )}
      </div>
    </Layout>
  );
}
